name: Build Linux
on: ['push']
jobs:
  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Update system
        run: sudo apt update
      - name: Install package
        run: make install
      - name: Test package
        run: make test
      - name: Build distribution
        run: make build
  
